apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30017
  selector:
    app: mongodb
  type: NodePort
