apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fs-pvc
  namespace: cloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-client
