apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-fs
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.0.132
    path: /mnt/nfs/cloud-fs-pvc-pvc-984b5d47-806c-4ce2-87db-f84fe445b756
