image:
  repository: nextcloud
  flavor: apache
  tag: 31.0.0
  pullPolicy: IfNotPresent

replicaCount: 1

ingress:
  enabled: false

nextcloud:
  host: nextcloud.v34l.com
  username: admin
  password: root
  existingSecret:
    enabled: false
  update: 0
  containerPort: 80
  datadir: /var/www/html/data
  trustedDomains:
    - nextcloud.v34l.com
    - localhost
    
internalDatabase:
  enabled: false

mariadb:
  enabled: false

postgresql:
  enabled: true
  auth:
    username: nextcloud
    password: strongpassword
    database: nextcloud
  primary:
    persistence:
      enabled: true
      storageClass: "csi-rbd-sc"
      accessMode: ReadWriteOnce
      size: 5Gi
  
redis:
  enabled: true
  architecture: standalone
  persistence:
    enabled: true
    storageClass: "csi-rbd-sc"
    accessMode: ReadWriteOnce
    size: 2Gi

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  existingClaim: fs-pvc
  mountPath: /var/www/html/data
  nextcloudConfig:
    enabled: true
    storageClass: "csi-rbd-sc"
    accessMode: ReadWriteOnce
    size: 2Gi
  nextcloudDatabase:
    enabled: true
    storageClass: "csi-rbd-sc"
    accessMode: ReadWriteOnce
    size: 5Gi

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"
    
livenessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: false
  initialDelaySeconds: 240
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

startupProbe:
  enabled: false
  exec:
    command:
      - /bin/sh
      - -c
      - "curl -f http://localhost:80/status.php || exit 1"
  initialDelaySeconds: 240
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 60
  successThreshold: 1
