image:
  repository: nextcloud
  flavor: apache
  tag: 31.0.0
  pullPolicy: IfNotPresent

replicaCount: 1

ingress:
  enabled: false

nextcloud:
  host: nextcloud.v34l.com
  username: admin
  password: root
  existingSecret:
    enabled: false
  update: 0
  containerPort: 80
  datadir: /var/www/html/data
  trustedDomains:
    - nextcloud.v34l.com
    - localhost

internalDatabase:
  enabled: false

mariadb:
  enabled: false

postgresql:
  enabled: true
  auth:
    username: nextcloud
    password: strongpassword
    database: nextcloud
  primary:
    persistence:
      enabled: true
      storageClass: "local-path"
      accessMode: ReadWriteOnce
      size: 3Gi

redis:
  enabled: true
  architecture: standalone
  persistence:
    enabled: true
    storageClass: "csi-rbd-sc"
    accessMode: ReadWriteOnce
    size: 2Gi

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  existingClaim: fs-pvc
  mountPath: /var/www/html/data
  nextcloudConfig:
    enabled: true
    storageClass: "local-path"
    accessMode: ReadWriteOnce
    size: 2Gi
  nextcloudDatabase:
    enabled: true
    storageClass: "local-path"
    accessMode: ReadWriteOnce
    size: 5Gi

resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1"
livenessProbe:
  enabled: false
  initialDelaySeconds: 300
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5
  successThreshold: 1
readinessProbe:
  enabled: false
  initialDelaySeconds: 300
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5
  successThreshold: 1
startupProbe:
  enabled: false
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30
  successThreshold: 1

collabora:
  enabled: true

  autoscaling:
    # enable autocaling, please check collabora README.md first
    enabled: false

  collabora:
    ## HTTPS nextcloud domain, if needed
    aliasgroups:
       - host: "https://nextcloud.v34l.com:443"

    # set extra parameters for collabora
    # you may need to add --o:ssl.termination=true
    extra_params: --o:ssl.enable=false

    ## Specify server_name when the hostname is not reachable directly for
    # example behind reverse-proxy. example: collabora.domain
    server_name: collabora.nextcloud.v34l.com

    existingSecret:
      # set to true to to get collabora admin credentials from an existin secret
      # if set, ignores collabora.collabora.username and password
      enabled: true
      # name of existing Kubernetes Secret with collboara admin credentials
      secretName: "collabora-secret"
      usernameKey: "username"
      passwordKey: "password"

  # setup ingress
  ingress:
    # enable ingress for collabora online
    enabled: false
    className: ""
    # please check collabora values.yaml for nginx/haproxy annotations examples
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
        - path: /
          pathType: ImplementationSpecific
    tls: []
    #  - secretName: collabora-ingress-tls
    #    hosts:
    #      - collabora.domain

  # see collabora helm README.md for recommended values
  resources: {}
