apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: m15ty-com
  namespace: gateway
spec:
  secretName: m15ty-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.m15ty.com"
