apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-home
  source:
    repoURL: https://github.com/alexvegas22/k8s-home
    targetRevision: talos
    path: system/cilium
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
