apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  destination:
    namespace: valkey-system
    server: https://kubernetes.default.svc

  project: k8s-home

  source:
    repoURL: https://github.com/alexvegas22/k8s-home.git
    path: operator/valkey
    targetRevision: talos

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
