---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8s-home
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: talos
  url: https://github.com/alexvegas22/k8s-home
