---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: argo-cd
  namespace: flux-system
spec:
  interval: 1h
  url: https://argoproj.github.io/argo-helm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 1h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: valkey
  namespace: flux-system
spec:
  interval: 1h
  url: https://valkey.io/valkey-helm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: forgejo
  namespace: flux-system
spec:
  interval: 1h
  url: oci://code.forgejo.org/forgejo-helm
  type: oci
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  interval: 1h
  url: https://nextcloud.github.io/helm/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 1h
  url: https://immich-app.github.io/immich-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.releases.hashicorp.com
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  interval: 1h
  url: https://guerzon.github.io/vaultwarden
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.goharbor.io
