global:
  domain: argocd.m15ty.com

server:
  ingress:
    enabled: false

  service:
    type: ClusterIP

  certificate:
    enabled: true
    issuer:
      group: cert-manager.io
      kind: ClusterIssuer
      name: letsencrypt-prod

  config:
    admin.enabled: true
    url: https://argocd.m15ty.com

configs:
  cm:
    create: true
    url: https://argocd.m15ty.com
    kustomize.buildOptions: --enable-helm
  # secret:
  #   githubSecret:
  #     secretKeyRef:
  #       name: argocd-webhook
  #       key: github-secret-key

dex:
  enabled: false

controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true

applicationSet:
  metrics:
    enabled: true
