---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
data:
  config.yaml: |
    storage:
      type: sqlite
      path: /data/gatus.db

    endpoints:
      - name: blog-v34l
        url: https://blog.m15ty.com
        interval: 30s
        conditions:
          - "[STATUS] == 200"
      - name: nextcloud
        url: https://nextcloud.m15ty.com
        interval: 30s
        conditions:
          - "[STATUS] == 200"
      - name: vaultwarden
        url: https://vaultwarden.m15ty.com
        interval: 30s
        conditions:
          - "[STATUS] == 200"
      - name: immich
        url: https://immich.m15ty.com
        interval: 30s
        conditions:
          - "[STATUS] == 200"
      - name: htb
        url: https://htb.m15ty.com
        interval: 30s
        conditions:
          - "[STATUS] == 200"
      - name: argocd
        url: https://argocd.m15ty.com
        interval: 30s
        conditions:
          - "[STATUS] == 200"
