apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: csi-app
resources:
  - ceph-config-map.yaml
  - csi-config-map.yaml
  - csi-rbdplugin-provisioner.yaml
  - csi-rbdplugin.yaml
  - csi-rbd-sc.yaml

