apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/ingress.yaml
helmCharts:
  - name: nextcloud
    version: "6.6.9"
    repo: https://nextcloud.github.io/helm/
    releaseName: "nextcloud"
    namespace: cloud
    valuesFile: "helm/values.yaml"
