apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-dns-updater
spec:
  schedule: "15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cloudflare-dns-updater
            image: ghcr.io/alexvegas22/cloudflare-dns-updater:main
            env:
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-secret
                  key: api-token
            resources:
              requests:
                cpu: "100m"
                memory: "64Mi"
              limits:
                cpu: "500m"
                memory: "128Mi"
          restartPolicy: OnFailure
