# yaml-language-server: $schema=https://code.forgejo.org/forgejo-helm/forgejo-helm/raw/branch/main/values.schema.json
service:
  ssh:
    port: 22
    type: LoadBalancer
    loadBalancerIP: 142.137.247.76

httpRoute:
  enabled: true
  annotations: {}
  parentRefs:
    - name: main-gateway #name of the gateway resource
      namespace: gateway #name space where gateway resource running
  hostnames:
    - git.v34l.com
  matches:
    path:
      type: PathPrefix
      value: '/'
    timeouts: {}
      # request: 10s  #Maximum time the Gateway waits to complete the full client request and response cycle.
      # backendRequest: 10s # Maximum time the Gateway waits for a response from the backend service.
  filters: []
  # - type: RequestHeaderModifier
  #   requestHeaderModifier:
  #     set:
  #       - name: X-Forwarded-Proto
  #         value: https
  port:
  terminate: true

gitea:
  admin:
    existingSecret: forgejo-admin-secret
    email: forgejo@v34l.com
  config:
    actions:
      enabled: true
      DEFAULT_ACTIONS_URL: https://github.com
    server:
      ROOT_URL: https://git.v34l.com/
      PROTOCOL: http
      OFFLINE_MODE: false
      DOMAIN: git.v34l.com
      LFS_START_SERVER: true
      SSH_DOMAIN: ssh.git.v34l.com
    picture:
      ENABLE_FEDERATED_AVATAR: true
      DISABLE_GRAVATAR: false
    service:
      DISABLE_REGISTRATION: true
      DEFAULT_ALLOW_CREATE_ORGANIZATION: false
    oauth2_client:
      REGISTER_EMAIL_CONFIRM: false
      OPENID_CONNECT_SCOPES: "openid profile email offline_access"
      ENABLE_AUTO_REGISTRATION: true
      USERNAME: nickname
      UPDATE_AVATAR: false
      ACCOUNT_LINKING: auto
    repository:
      DEFAULT_BRANCH: main
      MAX_CREATION_LIMIT: 0
      GO_GET_CLONE_URL_PROTOCOL: ssh
      ALLOW_FORK_WITHOUT_MAXIMUM_LIMIT: false
    cache:
      ADAPTER: redis
      HOST: redis://forgejo-cache-valkey.forgejo.svc.cluster.local:6379/0
    session:
      PROVIDER: redis
      PROVIDER_CONFIG: redis://forgejo-cache-valkey.forgejo.svc.cluster.local:6379/1
    queue:
      TYPE: redis
      CONN_STR: redis://forgejo-cache-valkey.forgejo.svc.cluster.local:6379/2
    openid:
      ENABLE_OPENID_SIGNIN: false
      ENABLE_OPENID_SIGNUP: false
    lfs:
      STORAGE_TYPE: local
      PATH: /data/forgejo/lfs
  # oauth:
  #   - name: "authentik"
  #     provider: openidConnect
  #     existingSecret: forgejo-oauth-secret
  #     autoDiscoverUrl: "https://auth.v34l.com/application/o/forgejo/.well-known/openid-configuration"
  #     scopes: "openid profile email offline_access"
  #     adminGroup: admin
  #     groupClaimName: groups
  #     groupTeamMap: '{"club-lanets": {"Lan_ETS": ["Members"]},"exec-lanets": {"Lan_ETS": ["Owners"]},"exec-cedille": {"cedille": ["Owners"]},"exec-conjure": {"conjure": ["Owners"]}}'
  #     groupTeamMapRemoval: "true"
  additionalConfigSources:
    - secret:
        secretName: forgejo-db-config

persistence:
  enabled: true
  create: true
  size: 50Gi
  claimName: forgejo-data-claim
  storageClass: nfs-client
  accessModes:
    - ReadWriteMany
