apiVersion: apps/v1
kind: Deployment
metadata:
  name: v34l
  labels:
    app: v34l
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v34l
  template:
    metadata:
      labels:
        app: v34l
    spec:
      containers:
      - name: v34l
        image: kennethreitz/v34l
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: v34l
  namespace: default
  labels:
    app: v34l
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: v34l
  type : ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: v34l-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.tls: "true" # Enables HTTPS
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure # Allow both HTTP and HTTPS
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  ingressClassName: traefik 
  rules:
  - host: v34l.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: v34l
            port:
              number: 80
  tls:
    - hosts:
      - v34l.com
      secretName: v34l-tls
