apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/ingress.yaml
helmCharts:
  - name: immich
    version: "0.9.2"
    repo: https://immich-app.github.io/immich-charts
    releaseName: "immich"
    namespace: cloud
    valuesFile: "helm/values.yaml"
