---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
data:
  config.yaml: |
    storage:
      type: sqlite
      path: /data/gatus.db
    web:
      port: 8080
    endpoints:
      - name: acets-prodv2-cedille-club
        group: production
        url: "https://acets.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"
      - name: argocd-mgmtv2-cedille-club
        group: production
        url: "https://argocd.mgmtv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"
      - name: atelier-crabe-cedille-club
        group: production
        url: "https://atelier.crabe.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"
      - name: auth-etsmtl-club
        group: production
        url: "https://auth.etsmtl.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: calidum-rotae-prodv2-cedille-club
        group: production
        url: "https://calidum-rotae.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: campusparent-prodv2-cedille-club
        group: production
        url: "https://campusparent.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: cedille-etsmtl-ca
        group: production
        url: "https://cedille.etsmtl.ca/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: cedille-etsmtl-club
        group: production
        url: "https://cedille.etsmtl.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: cedille-prodv2-cedille-club
        group: production
        url: "https://cedille.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: collabora-nextcloud-etsmtl-club
        group: production
        url: "https://collabora-nextcloud.etsmtl.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: comets-ets-com
        group: production
        url: "https://comets-ets.com/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: comets-etsmtl-ca
        group: production
        url: "https://comets.etsmtl.ca/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: comets-prodv2-cedille-club
        group: production
        url: "https://comets.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: commande-fraternitedupiranha-com
        group: production
        url: "https://commande.fraternitedupiranha.com/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: conjure-etsmtl-ca
        group: production
        url: "https://conjure.etsmtl.ca/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: coroot-etsmtl-club
        group: production
        url: "https://coroot.etsmtl.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: coroot-prodv2-cedille-club
        group: production
        url: "https://coroot.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: crabe-etsmtl-ca
        group: production
        url: "https://crabe.etsmtl.ca/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: docmost-etsmtl-club
        group: production
        url: "https://docmost.etsmtl.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: dronolab-etsmtl-ca
        group: production
        url: "https://dronolab.etsmtl.ca/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: esports-prodv2-cedille-club
        group: production
        url: "https://esports.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: evovelo-etsmtl-ca
        group: production
        url: "https://evovelo.etsmtl.ca/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: evovelo-prodv2-cedille-club
        group: production
        url: "https://evovelo.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: forom-prodv2-cedille-club
        group: production
        url: "https://forom.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: git-etsmtl-club
        group: production
        url: "https://git.etsmtl.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: grafana-prodv2-cedille-club
        group: production
        url: "https://grafana.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: habitek-ca
        group: production
        url: "https://habitek.ca/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: habitek-prodv2-cedille-club
        group: production
        url: "https://habitek.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: influxdb-prodv2-cedille-club
        group: production
        url: "https://influxdb.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: ingenieuses-ca
        group: production
        url: "https://ingenieuses.ca/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: integrale-etsmtl-ca
        group: production
        url: "https://integrale.etsmtl.ca/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: jdgets-outlinewiki-prodv2-cedille-club
        group: production
        url: "https://jdgets-outlinewiki.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: kubero-etsmtl-club
        group: production
        url: "https://kubero.etsmtl.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: markets-algoets-ca
        group: production
        url: "https://markets.algoets.ca/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: markets-dev-cedille-club
        group: staging
        url: "https://markets.dev.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: markets-prodv2-cedille-club
        group: production
        url: "https://markets.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: matomo-etsmtl-club
        group: production
        url: "https://matomo.etsmtl.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: matomo-prodv2-cedille-club
        group: production
        url: "https://matomo.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: n8n-prodv2-cedille-club
        group: production
        url: "https://n8n.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: nextcloud-etsmtl-club
        group: production
        url: "https://nextcloud.etsmtl.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: penpot-prodv2-cedille-club
        group: production
        url: "https://penpot.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: plane-prodv2-cedille-club
        group: production
        url: "https://plane.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: planifets-prodv2-cedille-club
        group: production
        url: "https://planifets.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: planka-etsmtl-club
        group: production
        url: "https://planka.etsmtl.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: pr-241-cedille-prodv2-cedille-club
        group: production
        url: "https://pr-241.cedille.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: pr-259-cedille-prodv2-cedille-club
        group: production
        url: "https://pr-259.cedille.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: pr-72-synapse-prodv2-cedille-club
        group: production
        url: "https://pr-72.synapse.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: pr-73-synapse-prodv2-cedille-club
        group: production
        url: "https://pr-73.synapse.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: pr-77-synapse-prodv2-cedille-club
        group: production
        url: "https://pr-77.synapse.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: pr-85-synapse-prodv2-cedille-club
        group: production
        url: "https://pr-85.synapse.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: preci-etsmtl-ca
        group: production
        url: "https://preci.etsmtl.ca/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: raconteurs-etsmtl-ca
        group: production
        url: "https://raconteurs.etsmtl.ca/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: saveursdegenie-etsmtl-ca
        group: production
        url: "https://saveursdegenie.etsmtl.ca/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: supabase-prodv2-cedille-club
        group: production
        url: "https://supabase.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: synapsets-etsmtl-ca
        group: production
        url: "https://synapsets.etsmtl.ca/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: trema-prodv2-cedille-club
        group: production
        url: "https://trema.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: twenty-prodv2-cedille-club
        group: production
        url: "https://twenty.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: vault-etsmtl-club
        group: production
        url: "https://vault.etsmtl.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: vault-prodv2-cedille-club
        group: production
        url: "https://vault.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: vaultwarden-etsmtl-club
        group: production
        url: "https://vaultwarden.etsmtl.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: wiki-capra-etsmtl-ca
        group: production
        url: "https://wiki.capra.etsmtl.ca/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: wiki-cedille-club
        group: production
        url: "https://wiki.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"

      - name: wiki-etsmtl-club
        group: production
        url: "https://wiki.etsmtl.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"
      - name: wiki-minikube-local
        group: production
        url: "https://wiki.minikube.local/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"
      - name: wiki-prodv2-cedille-club
        group: production
        url: "https://wiki.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"
      - name: wiki-sonia-etsmtl-ca
        group: production
        url: "https://wiki.sonia.etsmtl.ca/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"
      - name: wiki-synapsets-prodv2-cedille-club
        group: production
        url: "https://wiki.synapsets.prodv2.cedille.club/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"
      - name: www-ingenieuses-ca
        group: production
        url: "https://www.ingenieuses.ca/"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[CERTIFICATE_EXPIRATION] > 48h"
