apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: v34l-blog
  namespace: argocd
spec:
  destination:
    namespace: hugo
    server: https://v34l.com
  project: k8s-home
  source:
    path: apps/v34l-blog
    repoURL: git@github.com:alexvegas22/k8s-home.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
