apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: v34l-blog
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: website=ghcr.io/alexvegas22/0xv34l:main
    argocd-image-updater.argoproj.io/website.update-strategy: digest
spec:
  destination:
    namespace: hugo
    server: https://kubernetes.default.svc
  project: k8s-home
  source:
    path: apps/v34l-blog/resources
    repoURL: https://github.com/alexvegas22/k8s-home.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
