---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: v34l-blog
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/v34l-blog
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-home
  targetNamespace: hugo
