env:
  REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
  DB_HOSTNAME: postgresql.cloud.svc.cluster
  DB_USERNAME: immich
  DB_DATABASE_NAME: immich
  IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'

postgresql.global.postgresql.auth.existingSecret: postgres-secret
image:
  tag: v1.119.0

immich:
  metrics:
    enabled: false

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false

immich:
  persistence:
    library:
      existingClaim: fs-pvc

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent
  ingress:
    main:
      enabled: false

machine-learning:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-machine-learning
    pullPolicy: IfNotPresent
  env:
    TRANSFORMERS_CACHE: /cache
  persistence:
    cache:
      enabled: true
      size: 10Gi
      type: pvc
      accessMode: ReadWriteMany
      storageClass: nfs-client
