apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
spec:
  project: k8s-home

  destination:
    namespace: forgejo
    server: https://kubernetes.default.svc

  source:
    path: apps/forgejo
    repoURL: https://github.com/alexvegas22/k8s-home.git
    targetRevision: HEAD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
