apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forgejo
resources:
  - namespace.yaml
  - cnpg.cluster.yaml
  - forgejo-helmrelease.yaml
  - valkey-helmrelease.yaml

configMapGenerator:
  - name: forgejo-values
    files:
      - values.yaml=base/forgejo.values.yaml
  - name: forgejo-cache-valkey-values
    files:
      - values.yaml=base/valkey.values.yaml

configurations:
  - kustomizeconfig.yaml
