apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cnpg.cluster.yaml

helmCharts:
  - name: valkey
    releaseName: forgejo-cache
    repo: https://valkey.io/valkey-helm/
    version: 0.9.3
    valuesFile: helm/valkey.values.yaml
    namespace: forgejo

  - name: forgejo
    releaseName: forgejo
    repo: oci://code.forgejo.org/forgejo-helm
    version: 17.1.0
    valuesFile: helm/forgejo.values.yaml
    namespace: forgejo
