apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: harbor
  namespace: harbor
resources:
  - resources/ingress.yaml
helmCharts:
  - name: harbor
    version: "1.16"
    repo: "https://helm.goharbor.io"
    releaseName: "harbor"
    namespace: harbor
    valuesFile: "helm/values.yaml"
