apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: htb
  namespace: htb
spec:
  destination:
    namespace: htb
    server: https://v34l.com
  project: k8s-home
  source:
    path: apps/htb
    repoURL: git@github.com:alexvegas22/k8s-home.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
