---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 1h
  releaseName: vault
  chart:
    spec:
      chart: vault
      version: "0.29.1"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: vault-values
      valuesKey: values.yaml
