apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: vault
  namespace: vault
resources:
  - resources/ingress.yaml
helmCharts:
  - name: vault
    version: "0.29.1"
    repo: "https://helm.releases.hashicorp.com"
    releaseName: "vault"
    namespace: vault
    valuesFile: "helm/values.yaml"
