apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/ingress.yaml

patches:
  - target:
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cm
        namespace: argocd
      data:
        kustomize.buildOptions: --enable-helm
helmCharts:
- name: argo-cd
  repo: oci://ghcr.io/argoproj/argo-helm
  version: 7.8.23
  releaseName: argocd
  apiVersions:
  - monitoring.coreos.com/v1
  valuesFile: helm/values.yaml
