apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-cd
  repo: oci://ghcr.io/argoproj/argo-helm
  version: 7.8.23
  releaseName: argocd
  apiVersions:
  - monitoring.coreos.com/v1
  valuesFile: helm/values.yaml
